version: '2'

services:
  gossa-server:
    image: docker.io/pknw1/gossa:latest
    container_name: gossa
    restart: always
    read_only: true
    environment:
      - VIRTUAL_HOST=cloud.pknw1.co.uk
      - VIRTUAL_PORT=8001
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    networks:
      proxy:
    # uncomment to set resource usage limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 250m
    #       pids: 1024

    volumes:
      - /media/movies:/shared/readonly/media/movies:ro
      - /media/tv:/shared/readonly/media/tv:ro
      - /downloads:/shared/readonly/downloads:ro
      - /media/uploads:/shared/uploads
      - /dev/fuse:/dev/fuse

networks:
  proxy:
    external: true
