name: deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and release on dockerhub
      uses: docker/build-push-action@v6
      with:
        file: support/build.Dockerfile
        push: true
        platforms: linux/amd64
        tags: pknw1/gossa:latest,pknw1/gossa:${{github.ref_name}}

    - name: Build all artifacts
      run: make build-all

    - name: "Release gh release versioned"
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "builds/*"
        bodyFile: "builds/buildout"
        token: ${{ secrets.GH_ORG }}

    - name: "Release gh release latest"
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest
        allowUpdates: true
        artifacts: "builds/*"
        bodyFile: "builds/buildout"
        token: ${{ secrets.GH_ORG }}
